name: magento
recipe: lemp
config:
  php: '8.1'
  webroot: pub
  config:
    vhosts: nginx.conf.lando
services:
  appserver:
    build_as_root:
      - apt-get update -qq
      - apt-get install libxslt1-dev cron -yqq
      - docker-php-ext-install xsl sockets
    run_as_root:
      - service cron start
  search:
    type: elasticsearch:7
  mail:
    type: mailhog
    hogfrom:
      - appserver
  messaging:
    type: compose
    app_mount: false
    services:
      image: rabbitmq
      command: docker-entrypoint.sh rabbitmq-server
      environment:
        RABBITMQ_DEFAULT_USER: magento
        RABBITMQ_DEFAULT_PASS: magento
tooling:
  magento:
    service: appserver
    cmd: bin/magento
  init-magento:
    service: appserver
    cmd: |
      bin/magento setup:install \
        --base-url=https://magento.lndo.site \
        --db-host=database \
        --db-name=lemp \
        --db-user=lemp \
        --db-password=lemp \
        --admin-firstname=Tommaso \
        --admin-lastname=Bailetti \
        --admin-email=bailetti.tommaso@gmail.com \
        --admin-user=admin \
        --admin-password=admin123 \
        --elasticsearch-host=search \
        --amqp-host=messaging \
        --amqp-user=magento \
        --amqp-password=magento \
        --language=it_IT \
        --currency=EUR \
        --timezone=Europe/Rome \
        --use-rewrites=1 \
      bin/magento cron:install
  remove-magento:
    service: appserver
    cmd:
      - bin/magento cron:remove
      - bin/magento setup:uninstall -n
  sample-data:
    service: appserver
    cmd:
      - bin/magento sampledata:deploy
      - bin/magento setup:upgrade
