name: magento
recipe: lemp
config:
  php: '8.1'
  webroot: pub
services:
  appserver:
    build_as_root:
      - apt-get update -qq
      - apt install libxslt1-dev -yqq
      - docker-php-ext-install xsl sockets
    run:
      - composer i
  search:
    type: elasticsearch:7
tooling:
  magento:
    service: appserver
    cmd: bin/magento
